name = "discord-book-poll-bot"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "POLLS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[triggers]
crons = ["*/5 * * * *"]