name = "discord-book-poll-bot"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "POLLS_DB"
database_name = "discord-polls"
database_id = "782b5ef7-cf19-4e2e-b6cc-7d9d680a763b"

[triggers]
crons = ["*/5 * * * *"]
