name = "discord-book-poll-bot"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "POLLS_DB"
database_name = "discord-polls"
database_id = "your-d1-database-id"

[triggers]
crons = ["*/5 * * * *"]